Julissa_Portafolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('portafolio.urls', namespace='portafolio')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portafolio/urls.py
from django.urls import path

from .views import SignInView, SignUpView, SignOutView, HomeTemplateView, BlogListView, BlogsDetailView, PortfolioAndCursoListView

app_name = 'portafolio'

urlpatterns = [
  # Home
  path('', HomeTemplateView.as_view(), name='home'),

  # Accounts
  path('signup/', SignUpView.as_view(), name='signup'),
  path('signin/', SignInView.as_view(), name='signin'),
  path('signout/', SignOutView.as_view(), name='signout'),

  # Blogs
  path('blog/', BlogListView.as_view(), name='blog_list'),
  path('blog/<int:blog_id>/', BlogsDetailView.as_view(), name='blog_details'),

  # Portfolio y Curso
  path('portfolio/', PortfolioAndCursoListView.as_view(), name='portfolio_and_projects'),
]

portafolio/models.py
import datetime
from datetime import date

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, Group, Permission, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
  def create_user(self, email, password=None, **extra_fields):
    if not email:
      raise ValueError('Correo Electronico Obligatorio')
    email = self.normalize_email(email)
    user = self.model(email=email, **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self, email, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)
    if extra_fields.get('is_staff') is not True:
      raise ValueError('El superusuario debe tener is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('El superusuario debe tener is_superuser=True.')
    superuser = SuperUser(email=email, **extra_fields)
    superuser.set_password(password)
    superuser.save(using=self._db)
    return superuser


class CustomUser(AbstractUser):
  birth_day = models.DateField(_('Fecha Nacimiento'))
  first_name = models.CharField(_('Nombre'), max_length=30)
  last_name = models.CharField(_('Apellido'), max_length=30)
  username = models.CharField(_('Usuario'), max_length=20, unique=True)
  email = models.EmailField(_('Correo Electrónico'), unique=True)
  is_staff = models.BooleanField(_('Admin'), default=False)
  is_active = models.BooleanField(_('Activo'), default=True)

  objects = CustomUserManager()

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['birth_day', 'first_name', 'last_name', 'username']

  class Meta:
    verbose_name = 'Usuario'
    verbose_name_plural = 'Usuarios'

  def __str__(self):
    return self.email


class SuperUser(CustomUser):
  class Meta:
    verbose_name = 'Super Usuario'
    verbose_name_plural = 'Super Usuarios'


class User(CustomUser):
  class Meta:
    verbose_name = 'Usuario Normal'
    verbose_name_plural = 'Usuarios Normales'


class Blog(models.Model):
  title = models.CharField(max_length=50)
  description = models.TextField()
  image = models.ImageField(upload_to='blogs_Julissa/images')
  date = models.DateField(default=datetime.date.today)

  def __str__(self) -> str:
    return self.title


class Portfolio(models.Model):
  title = models.CharField(max_length=50)
  description = models.CharField(max_length=250)
  image = models.ImageField(upload_to='portfolio_Julissa/images')
  url = models.URLField(blank=True)
  date = models.DateField(default=date.today)

  def __str__(self) -> str:
    return self.title


class Curso(models.Model):
  institucion_del_curso = models.CharField(max_length=225)
  descripcion_curso = models.TextField()
  fecha_curso = models.DateField()
  numero_horas = models.PositiveIntegerField()

  def __str__(self):
    return f'{self.descripcion_curso} - {self.institucion_del_curso}'

portafolio/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _

from .models import User


class UserSignUpForm(UserCreationForm):
  email = forms.EmailField(required=True, label='Correo Electrónico')

  class Meta:
    model = User
    fields = ('email', 'first_name', 'last_name', 'username', 'birth_day', 'password1', 'password2')

  def clean_email(self):
    email = self.cleaned_data.get('email')
    if User.objects.filter(email=email).exists():
      raise forms.ValidationError('Ya existe un usuario con este correo electrónico.')
    return email

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field_name, field in self.fields.items():
      field.widget.attrs.update({'style': 'border-radius: 0.25rem; padding: 0.5rem; color:black; background: linear-gradient(135deg, #6f42c1, #9b59b6, #d1a3ff); color:white;'})


class UserSignInForm(AuthenticationForm):
  class Meta:
    model = User
    User.email = forms.EmailField(required=True)
    fields = ('email', 'password')

  def clean(self):
    cleaned_data = super().clean()
    email = cleaned_data.get('email')
    password = cleaned_data.get('password')

    if email and password:
      user = authenticate(email=email, password=password)
      if user is None:
        raise forms.ValidationError(_('Las credenciales son incorrectas.'))
    return cleaned_data

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field_name, field in self.fields.items():
      field.widget.attrs.update({'style': 'border-radius: 0.25rem; padding: 0.5rem; background: linear-gradient(135deg, #6f42c1, #9b59b6, #d1a3ff);'})

portafolio/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView

from .forms import UserSignUpForm, UserSignInForm
from .models import User, Blog, Portfolio, Curso


class HomeTemplateView(TemplateView):
  template_name = 'home.html'


class SignUpView(CreateView):
  model = User
  form_class = UserSignUpForm
  template_name = 'signup.html'
  success_url = reverse_lazy('portafolio:signin')

  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    return redirect(self.success_url)


class SignInView(LoginView):
  form_class = UserSignInForm
  template_name = 'signin.html'
  success_url = reverse_lazy('portafolio:home')

  @method_decorator(never_cache)
  def dispatch(self, request, *args, **kwargs):
    if request.user.is_authenticated:
      return redirect(self.success_url)
    return super().dispatch(request, *args, **kwargs)

  def form_valid(self, form):
    return super().form_valid(form)


class SignOutView(LoginRequiredMixin, LogoutView):
  next_page = reverse_lazy('portafolio:home')

  @method_decorator(never_cache)
  def dispatch(self, request, *args, **kwargs):
    response = super().dispatch(request, *args, **kwargs)
    logout(request)
    return response


class BlogListView(LoginRequiredMixin, ListView):
  model = Blog
  template_name = 'my_blogs_Julissa.html'
  context_object_name = 'blogs'
  login_url = reverse_lazy('portafolio:signin')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['total_blogs'] = self.get_queryset().count()
    context['title'] = 'Ing. Julissa'
    return context


class BlogsDetailView(LoginRequiredMixin, DetailView):
  model = Blog
  template_name = "blog_details_Julissa.html"
  context_object_name = "blog"
  login_url = reverse_lazy('portafolio:signin')

  def get_object(self, **kwargs):
    blog_id = self.kwargs.get('blog_id')
    return get_object_or_404(Blog, pk=blog_id)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = self.object.title
    return context


class PortfolioAndCursoListView(LoginRequiredMixin, TemplateView):
  template_name = 'portafolio.html'
  login_url = reverse_lazy('portafolio:signin')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = 'Ing. Julissa'
    context['projects'] = Portfolio.objects.all()
    context['cursos'] = Curso.objects.all()
    return context

templates/blog_details_Julissa.html
{% extends 'home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    <div>
        <div class="container">
            <h1 class="align-center">{{ blog.title }}</h1>
            <h2 class="my-2 h5 text-muted" style="color: white">{{ blog.date|date:'F jS Y' }}</h2>
            <br>
            <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="img-fluid img-blog-datails">
        </div>
        <div class="my-4">
            {{ blog.description|safe }}
        </div>
    </div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Julissa TRAKA{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'public/icon/julissa.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body class="text-light ">
{% include 'navbar.html' %}
<div class="container p-4 font-family-home container-welcome">
    {% block content %}
        {% include 'index.html' %}
    {% endblock %}
</div>

</body>
</html>

templates/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<div class="hero-section">
    <div class="welcome-content text-center">
        <div class="text">
            {% if user.is_authenticated %}
                <h1 class="fw-bold fade-in">¡Hola, {{ user.username }}!</h1>
            {% else %}
                <h1 class="fw-bold fade-in">¡Hola, Soy Julissa Lescano!</h1>
            {% endif %}
            <p class="tagline fade-in-delayed">Ingeniera en Software | Desarrollo Web | BackEnd</p>
            <p class="intro fade-in-more">Bienvenida a mi portafolio personal. Aquí comparto mi pasión por la
                tecnología, los proyectos que he desarrollado y las soluciones que me encanta crear.</p>
        </div>
        <div class="profile-img mt-4 fade-in-more">
            <img class="img-fluid rounded-circle custom-shadow"
                 src="{% static 'public/portafolio_Julissa/julissa.jpg' %}" alt="JavicSoftCode" width="150">
        </div>
        <a href="https://www.youtube.com/watch?v=RJRN5OxxaAU" class="btn btn-light mt-4 px-4 py-2 fade-in-delayed">Conóceme</a>
    </div>
</div>

templates/my_blogs_Julissa.html
{% extends 'home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    <h1 class="fs-2">Blogs</h1>
    <h3>Actualmente hay " {{ total_blogs }} " Blog{{ total_blogs|pluralize }}</h3>
    {% for blog in blogs %}
        <div class="py-3">
            <div class="card card-body bg-gradient">
                <div class="row">
                    <div class="col-3">
                        <img class="img-fluid img-size" src="{{ blog.image.url }}" alt="{{ blog.title }}">
                    </div>
                    <div class="col-9">
                        <h4>{{ blog.title }}</h4>
                        <p>{{ blog.description|striptags|truncatechars:100 }}</p>
                        <p>{{ blog.date|date:'M d Y'|upper }}</p>
                        <a href="{% url 'portafolio:blog_details' blog.id %}">{{ blog.title }}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-purple">
    <div class="container">
        {% if user.is_authenticated %}
            <a class="navbar-brand fw-bold fst-italic text-white" href="/">{{ user.username }}</a>
        {% else %}
            <a class="navbar-brand fw-bold fst-italic text-white" href="/">Mi Portafolio Web Django</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'portafolio:blog_list' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"
                           href="{% url 'portafolio:portfolio_and_projects' %}">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"
                           href="{% static 'public/portafolio_Julissa/julissa_vitae.pdf' %}" target="_blank">Download
                            CV</a>
                    </li>
                    <form method="POST" action="{% url 'portafolio:signout' %}" class="nav-link btn- text-white"
                          style="margin-top: 8">
                        {% csrf_token %}
                        <button class=" btn- text-white" type="submit" style="margin-top: 7px">Cerrar Sesión</button>
                    </form>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'portafolio:signin' %}">Iniciar Sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'portafolio:signup' %}">Registrarte</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/portafolio.html
{% extends 'home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    {% load static %}
    <div class="container">
        <header class="row bg-black text-center">
            <div class="col-md-4 my-auto">
                <img src="{% static 'public/portafolio_Julissa/julissa.jpg' %}" alt="JSC" class="img-JSC"/>
            </div>
            <div class="col-md-4 my-auto">
                <img src="{% static 'public/portafolio_Julissa/julissa.jpg' %}" alt="JSC" class="img-JSC"/>
            </div>
            <div class="col-md-4 my-auto">
                <img src="{% static 'public/portafolio_Julissa/julissa.jpg' %}" alt="JSC" class="img-JSC"/>
            </div>
        </header>
        <section class="row">
            <div class="col-md-12">
                <h1>¡Hola! Soy Julissa</h1>
                <p>
                    Estoy dando los primeros pasos en el desarrollo de software. Tengo un gran interés en aprender y
                    crecer en este campo.
                    Me atrae especialmente el desarrollo frontend de aplicaciones digitales, donde puedo combinar
                    creatividad y tecnología para
                    ofrecer experiencias visuales atractivas y fáciles de usar.
                </p>
                <p>
                    Actualmente, tengo un conocimiento básico de varios lenguajes de programación y una comprensión
                    básica de bases de datos,
                    lo que me da una base sólida para seguir explorando más herramientas y tecnologías. Estoy por
                    adquirir nuevas habilidades
                    y contribuir a proyectos que me permitan aprender junto a profesionales con más experiencia.
                </p>
            </div>
        </section>
    </div>

    <div class="row my-4 text-center">
        <h3>Mis Proyectos</h3>
        {% if projects %}
            {% for project in projects %}
                <div class="col-md-4 p-4 ">
                    <div class="card bg-gradient card-project">
                        <img src="{{ project.image.url }}" class="card-img-top img-size-portfolio"
                             alt="{{ project.title }}"/>
                        <div class="card-body ">
                            <h2>{{ project.title }}</h2>
                            <p>{{ project.description }}</p>
                            {% if project.url %}
                                <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm " target="__blank"
                                   rel="noreferrer">Visitar
                                    el Proyecto</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No hay proyectos disponibles.</p>
        {% endif %}
    </div>

    <div class="row my-4 text-center">
        <h3>Mis Cursos</h3>
        {% if cursos %}
            {% for curso in cursos %}
                <div class="col-md-4 p-4">
                    <div class="card bg-gradient card-project">
                        <div class="card-body">
                            <h2>{{ curso.institucion_del_curso }}</h2>
                            <p><strong>Descripción:</strong> {{ curso.descripcion_curso }}</p>
                            <p><strong>Fecha:</strong> {{ curso.fecha_curso }}</p>
                            <p><strong>Horas:</strong> {{ curso.numero_horas }} horas</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No hay cursos disponibles.</p>
        {% endif %}
    </div>
    
{% endblock %}

templates/signin.html
{% extends 'home.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% block content %}
    <main class="mainContent bg-gradient">
        <div class="container">
            <div class="row justify-content-center fade-in-more">
                <div class="col-lg-12">
                    <div class="card shadow-lg border-0 rounded-lg mt-5 bg-transparent">
                        <div class="card-header bg-transparent text-center">
                            <h3 class="text-white font-weight-bold my-1 h3">Iniciar Sesión</h3>
                        </div>
                        <div class="card-body bg-transparent">
                            <form method="POST" action="{% url 'portafolio:signin' %}" class="fade-in-more">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="form-group">
                                    {{ form.username.label_tag }}
                                    {{ form.username }}
                                    {{ form.username.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label_tag }}
                                    {{ form.password }}
                                    {{ form.password.errors }}
                                </div>
                                <div class="form-group mt-4 mb-0 text-center">
                                    <button type="submit" class="btn btn-primary-gradient btn-block">Entrar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/signup.html
{% extends 'home.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% block content %}
    <main class="mainContent bg-gradient">
        <div class="container">
            <div class="row justify-content-center fade-in-more">
                <div class="col-lg-12">
                    <div class="card shadow-lg border-0 rounded-lg mt-5 bg-transparent">
                        <div class="card-header bg-transparent text-center">
                            <h3 class="text-white font-weight-bold my-1 h3">Registrarte</h3>
                        </div>
                        <div class="card-body bg-transparent">
                            <form method="POST" action="{% url 'portafolio:signup' %}" class="fade-in-more">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="form-group">
                                    {{ form.email.label_tag }}
                                    {{ form.email }}
                                    {{ form.email.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.first_name.label_tag }}
                                    {{ form.first_name }}
                                    {{ form.first_name.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.last_name.label_tag }}
                                    {{ form.last_name }}
                                    {{ form.last_name.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.username.label_tag }}
                                    {{ form.username }}
                                    {{ form.username.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.birth_day.label_tag }}
                                    {{ form.birth_day }}
                                    {{ form.birth_day.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.password1.label_tag }}
                                    {{ form.password1 }}
                                    {{ form.password1.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.password2.label_tag }}
                                    {{ form.password2 }}
                                    {{ form.password2.errors }}
                                </div>
                                <div class="form-group mt-4 mb-0 text-center">
                                    <button type="submit" class="btn btn-primary-gradient btn-block">Crear Cuenta
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}